### ISSUE TITLE
New collaborator? Transfer ownership?

### ISSUE THREAD

**Issue by jonathantneal** [ahmadalfy/postcss-logical-properties#2]
I think there’s a big future for logical properties, and you’ve started a great effort here a few years ago.

We can support logical properties using `:dir(ltr)` and `:dir(rtl)` fallbacks, which themselves can be transformed for extensive backward compatibility.

I’ve added support for an additional 60 logical properties, as well as flow-relative values for `float`, `resize`, and `text-align`:

https://github.com/jonathantneal/postcss-logical-properties

Would you be interested in transferring the postcss-logical-properties name? Or allowing me to be a collaborator on npm and this repo, so that we can offer this to everyone under the “logical” namespace?

**Comment by jonathantneal** [comment]
Hey there. It’s been a few weeks. Here’s a demo of my new version. If I don’t hear back, I’ll go for a new name.

https://jonathantneal.github.io/postcss-logical-properties/

**Comment by ahmadalfy** [comment]
Apologies for the delayed reply I didn't get notification for your messages. Will respond shortly

**Comment by ahmadalfy** [comment]
@jonathantneal I apologize again for the delayed reply. Is it to late to add you to the collaborators list and work with you on it?

**Comment by jonathantneal** [comment]
Not at all. I have used a different namespace, but I still prefer to work together :)

**Comment by ahmadalfy** [comment]
Awesome, logical properties make great sense from where I come. I live in Egypt and we create dual direction websites all the time. What do you suggest we do? Add you to the collaborators list/give you ownership or move to the namespace you used?

**Comment by jonathantneal** [comment]
I prefer when there are multiple owners, like PostCSS has. This way, when one of us becomes busy, the other one is there to step in. It also means we have work together in good faith when we don’t see eye to eye on technical decisions, but I am an optimistic person in this regard. :) To that end, I’d love shared access to the npm namespace, but I hope you won’t remove yourself (unless you absolutely want nothing to do with this project, which I hope is not the case).

@ai, @MoOx, [CSS Logical Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) are Working Draft and implemented in Firefox. I think this repository should consider being hosted through the postcss group, to also increase awareness and shared ownership. I also think this sort of work should be put into cssnext. Thoughts?

@ahmadalfy, based on their responses, we can probably decide where this should be hosted. Thanks again so much for chatting with me about this!

**Comment by ahmadalfy** [comment]
This repository was added to the list of the plugins on postcss page but I think it is removed now because I was quite for some time. I am perfectly align with you, thank you for that great spirit.

I tried adding you to the collaborators, I think I also have to add you through [this](https://docs.npmjs.com/cli/owner) right?

**Comment by MoOx** [comment]
@jonathantneal Make sense. I don't use postcss nor cssnext this days so feel free to move forward, you definitely know the subject better than most people!

**Comment by ahmadalfy** [comment]
@jonathantneal I added you to the owners list

```
$ npm owner ls
ahmadalfy <ahmadalfy@*****.com>
jonathantneal <jonathantneal@*******.com>
```

**Comment by jonathantneal** [comment]
Thank you, @ahmadalfy! Will do, @MoOx. I’m also considering this immediate issue resolved. :)
